AdventureWorks/AwSales.Web/Models/ListaEmpleados.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AwSales.Web.Models
{
    public class ListaEmpleados
    {
        public int Id { get; set; }
        public DateTime FechaContrato { get; set; }

        public string NombreUsuario { get; set; }

        public string Titulo { get; set; }
    }
}

AdventureWorks/AwSales.Web/Areas/Administracion/Controllers/ConfiguracionController.cs
using AwSales.Funcionalidades.Configuracion;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AwSales.Web.Areas.Administracion.Controllers
{
    
    public class ConfiguracionController : Controller
    {
        // GET: Administracion/Configuracion
        public ActionResult Ver()
        {
            return View(new VerConfiguracionModelo());
        }

        public ActionResult IrAHome()
        {
            //quiero ir al home de la raiz
            return RedirectToAction("Contact", "Home", new { area = "" });
        }
    }
}

AdventureWorks/AwSales.Web/Controllers/EmpleadosController.cs
using AwSales.Web.Funcionalidades;
using AwSales.Web.Funcionalidades.EditarEmpleado;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AwSales.Web.Controllers
{
    
    public class EmpleadosController : Controller
    {
        // GET: Empleados
        public ActionResult Lista()
        {

            using (var listarEmpleados = new ListarEmpleados())
            {
                return View(listarEmpleados.Ejecutar());
            }
        }

        [HttpGet]
        public ActionResult CambiarCargo(int id)
        {
            using (var comando = new TraeEmpleadoParaCambioDeCargo())
            {
                return View(comando.Ejecutar(id));
            }
        }


        [HttpPost]
        public ActionResult CambiarCargo(CambiarCargoAEmpleadoComando modelo)
        {
            using (var comando = new CambiarCargoAEmpleado())
            {
                try
                {
                    comando.Ejecutar(modelo);
                    return RedirectToAction("Lista");
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", "Hubo un error al grabar");
                    using (var comando2 = new TraeEmpleadoParaCambioDeCargo())
                    {
                        return View(comando2.Ejecutar(modelo.EmpleadoId));
                    }
                }
            }
        }
    }
}

AdventureWorks/AwSales.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AwSales.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About2()
        {
            ViewBag.Message = "Your application description page.";

            return View("About");
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

AdventureWorks/AwSales.Web/Controllers/PersonasController.cs
using AwSales.Web.Funcionalidades.ListarPersonas;
using AwSales.Web.Funcionalidades.RegistrarPersona;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AwSales.Web.Controllers
{
    public class PersonasController : Controller
    {

        public ActionResult Lista(string filtro)
        {
            using (var listarPersonas = new ListarPersonaHandler())
            {

                return View(new FiltrarPersonasViewModel()
                {
                    Filtro = string.Empty,
                    Personas = listarPersonas.Ejecutar(filtro)
                });
            }
        }

        public PartialViewResult FiltrarPorNombre(string filtro)
        {
            using (var listarPersonas = new ListarPersonaHandler())
            {

                return PartialView("_PersonasEncontradas",
                        listarPersonas.Ejecutar(filtro)
                    );
            }
        }

        [HttpGet]
        public ActionResult Registrar()
        {
            return View(new RegistrarPersonaViewModel());
        }

        [HttpPost]
        public ActionResult Registrar(RegistrarPersonaViewModel modelo)
        {
            if (!ModelState.IsValid) return View(modelo);

            using (var registrarPersona = new RegistrarPersonaHandler())
            {
                try
                {
                    registrarPersona.Ejecutar(modelo);
                    return RedirectToAction("Lista");

                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", ex.Message);
                    return View(modelo);
                }

            }
        }

        [HttpGet]
        public PartialViewResult Editar(int id)
        {
            using (var buscarPersona = new VerPersonaHandler())
            {
                return PartialView("_Editar", buscarPersona.Execute(id));
            }
        }

        [HttpPost]
        public ActionResult Editar(ListaPersonasViewModel model)
        {
            return RedirectToAction("Lista");
        }

    }
}

AdventureWorks/AwSales.Web/Controllers/UbigeoController.cs
using AwSales.Web.XmlHelpers;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;

namespace AwSales.Web.Controllers
{
    public class UbigeoController : Controller
    {
        private UbigeoHelper _ubigeoHelper;

        protected override void Initialize(RequestContext requestContext)
        {
            base.Initialize(requestContext);
            _ubigeoHelper = new UbigeoHelper(Path.Combine(Server.MapPath("~/App_Data"), "Ubigeo.xml"));
        }

        [HttpGet]
        public JsonResult Departamentos()
        {
            // Json(el objeto que quieren devolver formato Json, behavior)
            return Json(_ubigeoHelper.GetDepartamentos().ToList(), JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult Provincias(string departamento)
        {
            return Json(_ubigeoHelper.GetProvincias(departamento).ToList(), JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult Distritos(string departamento, string provincia)
        {
            return Json(_ubigeoHelper.GetDistritos(departamento,provincia).ToList(), JsonRequestBehavior.AllowGet);
        }
    }
}

AdventureWorks/AwSales.Web/Areas/Administracion/Views/Configuracion/Ver.cshtml

@{
    ViewBag.Title = "Ver";
}

<h2>Ver</h2>

// voy a usar el action que redireccion al home de la raiz
@Html.ActionLink("Ir al Home Contact","IrAHome")

AdventureWorks/AwSales.Web/Areas/Administracion/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Configuracion</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Configuracion", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Ver Contacto", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

AdventureWorks/AwSales.Web/Views/Empleados/CambiarCargo.cshtml
@model AwSales.Web.Funcionalidades.EditarEmpleado.CambiarDeCargoAlEmpleadoModelo

@{
    ViewBag.Title = "CambiarCargo";
}

<h2>CambiarCargo</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>CambiarDeCargoAlEmpleadoModelo</h4>
        @Html.HiddenFor(model=>model.EmpleadoId)
        @*@Html.HiddenFor(model => model.CargoSeleccionado)*@
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CargoSeleccionado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(m=> m.CargoSeleccionado, Model.Cargos, new { @class = "form-control" } )
                @Html.ValidationMessageFor(model => model.CargoSeleccionado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

AdventureWorks/AwSales.Web/Views/Empleados/Lista.cshtml
@model IEnumerable<AwSales.Web.Models.ListaEmpleados>

@{
    ViewBag.Title = "Lista";
}

<h2>Lista</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FechaContrato)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NombreUsuario)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Titulo)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.HiddenFor(modelItem=> item.Id)
            @Html.DisplayFor(modelItem => item.FechaContrato)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NombreUsuario)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Titulo)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

AdventureWorks/AwSales.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

AdventureWorks/AwSales.Web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

AdventureWorks/AwSales.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

AdventureWorks/AwSales.Web/Views/Personas/Lista.cshtml
@model AwSales.Web.Funcionalidades.ListarPersonas.FiltrarPersonasViewModel

<h2>Lista</h2>
<p>
    @Html.ActionLink("Nuevo", "Registrar")
</p>

@*@using (Html.BeginForm("Lista",
                                        "Personas",
                                        null,
                                        FormMethod.Post,
                                        new { @class = "form-inline" }))
    {
        <div class="form-group col-sm-10 col-lg-10 col-xs-10 col-md-10">
            <input type="text" placeholder="Buscar Persona (Ej. Juan)"
                   name="Filtro" value="@Model.Filtro"
                   class="form-control" />
        </div>
        <input type="submit" value="Filtrar..." class="btn btn-success" />
    }*@

@using (Ajax.BeginForm("FiltrarPorNombre", "Personas",
                new AjaxOptions
                {
                    HttpMethod = "Get",
                    InsertionMode = InsertionMode.Replace,
                    UpdateTargetId = "ResultadoFiltro",

                },
                new
                {
                    id = "FiltrarPersonas",
                    @class = "form-inline"
                }
                ))
{
    <div class="form-group col-sm-10 col-lg-10 col-xs-10 col-md-10">
        <input type="text" placeholder="Buscar Persona (Ej. Juan)"
               name="Filtro" value="@Model.Filtro"
               class="form-control" />
    </div>
    <input type="submit" value="Filtrar..." class="btn btn-success" />
}

<div id="ResultadoFiltro">
    @if (Model.Personas.Count() > 0)
    {
        @Html.Partial("_PersonasEncontradas", Model.Personas)
    }
</div>

<div id="EditarPersonaForm"
     class="modal fade"
     tabindex="-1"
     role="dialog"
     aria-labelledby="EditarPersonalabel"
     aria-hidden="true"
     >
</div>

@section Scripts{
    @Scripts.Render("~/bundles/unobtrusiveajax")
}

AdventureWorks/AwSales.Web/Views/Personas/Registrar.cshtml
@model AwSales.Web.Funcionalidades.RegistrarPersona.RegistrarPersonaViewModel

@{
    ViewBag.Title = "Registrar";
}

<h2>Registrar</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>RegistrarPersonaViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.PersonType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PersonType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PersonType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NameStyle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.NameStyle)
                    @Html.ValidationMessageFor(model => model.NameStyle, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MiddleName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MiddleName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MiddleName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Suffix, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Suffix, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Suffix, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmailPromotion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmailPromotion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmailPromotion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Salario, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Salario, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Salario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DescuentoJudicial, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DescuentoJudicial, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DescuentoJudicial, "", new { @class = "text-danger" })
            </div>
        </div>

        <!-- seccion de listas en cascada -->
        <div id="persona-ubigeo">
            <div class="form-group">
                @Html.LabelFor(model => model.Departamento, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-3">
                    @Html.HiddenFor(model => model.Departamento, new { @id = "departamento_nombre", @class = "departamento" })
                    @Html.DropDownList("departamento", Model.Departamentos,
                    new { @id = "persona_departamento", @class = "form-control departamento" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Provincia, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-3">
                    @Html.HiddenFor(model => model.Provincia, new { @id = "provincia_nombre", @class = "provincia" })
                    @Html.DropDownList("provincia", Model.Provincias,
                    new { @id = "persona_provincia", @class = "form-control provincia" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Distrito, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-3">
                    @Html.HiddenFor(model => model.Distrito, new { @id = "distrito_nombre", @class = "distrito" })
                    @Html.DropDownList("distrito", Model.Distritos,
                    new { @id = "persona_distrito", @class = "form-control distrito" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar", "Lista")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/registrapersona")
}

AdventureWorks/AwSales.Web/Views/Personas/_Editar.cshtml
@model AwSales.Web.Funcionalidades.ListarPersonas.ListaPersonasViewModel

<div id="EditPersonaContainer">
    @using (Html.BeginForm("Editar", "Personas",FormMethod.Post,

                new
                {
                    id = "PersonaEditForm",
                    @class = "form-horizontal",
                    role = "form"
                }
                ))
    {
        @Html.AntiForgeryToken()

        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button"
                            class="close"
                            data-dismiss="modal"
                            aria-hidden="true">
                        &times;
                    </button>
                    <h4>Editando @Model.Nombre</h4>
                </div>
                <div class="modal-body">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.Id)

                    <div class="form-group">
                        @Html.LabelFor(model => model.Titulo, htmlAttributes: new { @class = "control-label col-md-3" })
                        <div class="col-md-9">
                            @Html.EditorFor(model => model.Titulo, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Titulo, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Tipo, htmlAttributes: new { @class = "control-label col-md-3" })
                        <div class="col-md-9">
                            @Html.EditorFor(model => model.Tipo, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Tipo, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-3" })
                        <div class="col-md-9">
                            @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.CorreoElectronico, htmlAttributes: new { @class = "control-label col-md-3" })
                        <div class="col-md-9">
                            @Html.EditorFor(model => model.CorreoElectronico, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.CorreoElectronico, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Grabar" class="btn btn-success" />
                    </div>
                </div>
            </div>
        </div>
    }


</div>

AdventureWorks/AwSales.Web/Views/Personas/_PersonasEncontradas.cshtml
@model IEnumerable<AwSales.Web.Funcionalidades.ListarPersonas.ListaPersonasViewModel>

<div class="container">
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Titulo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tipo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CorreoElectronico)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Titulo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Tipo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CorreoElectronico)
                </td>
                <td>
                    <div class="btn-group">
                        <button class="btn dropdown-toggle btn-xs"
                                data-toggle="dropdown">
                            <span>
                                <i class="glyphicon glyphicon-cog"></i>
                                <span class="caret"></span>
                            </span>
                        </button>
                        <ul class="dropdown-menu">
                            <li>
                                @Ajax.ActionLink(" ", "Editar", "Personas"
                   , new { id = item.Id }
                   , new AjaxOptions
                   {
                       HttpMethod = "Get",
                       InsertionMode = InsertionMode.Replace,
                       UpdateTargetId = "EditarPersonaForm"
                   }
                   ,
                   new
                   {
                       @class = "glyphicon glyphicon-trash",
                       data_toggle = "modal",
                       data_target = "#EditarPersonaForm"
                   }
                   )
                            </li>
                            <li>
                                @Html.ActionLink(" ", "Ver", new { id = item.Id }, new { @class = "glyphicon glyphicon-eye-open" })
                            </li>

                            <li>
                                @Html.ActionLink("Eliminar", "Eliminar", new { id = item.Id })


                            </li>

                        </ul>
                    </div>
                    |
                </td>
            </tr>
        }

    </table>
</div>

AdventureWorks/AwSales.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nombre de aplicación", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Administracion", "Ver", "Configuracion", new { area = "Administracion" }, null)</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>